--------------------------------------------------------
--  File created - Wednesday-July-08-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table S20_1_ROUTE
--------------------------------------------------------

  CREATE TABLE "SXS1987"."S20_1_ROUTE" 
   (	"ROUTE_NO" NUMBER(3,0), 
	"SOURCE_STATION_CODE" VARCHAR2(4), 
	"DEST_STATION_CODE" VARCHAR2(4), 
	"DISTANCE" VARCHAR2(4)
   ) ;
REM INSERTING into SXS1987.S20_1_ROUTE
SET DEFINE OFF;
Insert into SXS1987.S20_1_ROUTE (ROUTE_NO,SOURCE_STATION_CODE,DEST_STATION_CODE,DISTANCE) values (111,'NDL','MUM','1200');
Insert into SXS1987.S20_1_ROUTE (ROUTE_NO,SOURCE_STATION_CODE,DEST_STATION_CODE,DISTANCE) values (112,'MUM','NDL','1200');
Insert into SXS1987.S20_1_ROUTE (ROUTE_NO,SOURCE_STATION_CODE,DEST_STATION_CODE,DISTANCE) values (113,'NDL','BAN','1560');
Insert into SXS1987.S20_1_ROUTE (ROUTE_NO,SOURCE_STATION_CODE,DEST_STATION_CODE,DISTANCE) values (114,'BAN','NDL','1560');
Insert into SXS1987.S20_1_ROUTE (ROUTE_NO,SOURCE_STATION_CODE,DEST_STATION_CODE,DISTANCE) values (115,'NDL','HYD','1350');
Insert into SXS1987.S20_1_ROUTE (ROUTE_NO,SOURCE_STATION_CODE,DEST_STATION_CODE,DISTANCE) values (116,'HYD','NDL','1350');
Insert into SXS1987.S20_1_ROUTE (ROUTE_NO,SOURCE_STATION_CODE,DEST_STATION_CODE,DISTANCE) values (117,'MUM','HYD','1000');
Insert into SXS1987.S20_1_ROUTE (ROUTE_NO,SOURCE_STATION_CODE,DEST_STATION_CODE,DISTANCE) values (118,'HYD','MUM','1000');
Insert into SXS1987.S20_1_ROUTE (ROUTE_NO,SOURCE_STATION_CODE,DEST_STATION_CODE,DISTANCE) values (119,'MUM','BAN','950');
Insert into SXS1987.S20_1_ROUTE (ROUTE_NO,SOURCE_STATION_CODE,DEST_STATION_CODE,DISTANCE) values (120,'BAN','MUM','950');
Insert into SXS1987.S20_1_ROUTE (ROUTE_NO,SOURCE_STATION_CODE,DEST_STATION_CODE,DISTANCE) values (121,'PNQ','MUM','180');
Insert into SXS1987.S20_1_ROUTE (ROUTE_NO,SOURCE_STATION_CODE,DEST_STATION_CODE,DISTANCE) values (122,'MUM','PNQ','180');
Insert into SXS1987.S20_1_ROUTE (ROUTE_NO,SOURCE_STATION_CODE,DEST_STATION_CODE,DISTANCE) values (123,'NDL','JAI','275');
Insert into SXS1987.S20_1_ROUTE (ROUTE_NO,SOURCE_STATION_CODE,DEST_STATION_CODE,DISTANCE) values (124,'JAI','NDL','275');
--------------------------------------------------------
--  DDL for Index ROUTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SXS1987"."ROUTE_PK" ON "SXS1987"."S20_1_ROUTE" ("ROUTE_NO") 
  ;
--------------------------------------------------------
--  Constraints for Table S20_1_ROUTE
--------------------------------------------------------

  ALTER TABLE "SXS1987"."S20_1_ROUTE" ADD CONSTRAINT "ROUTE_PK" PRIMARY KEY ("ROUTE_NO")
  USING INDEX  ENABLE;
  ALTER TABLE "SXS1987"."S20_1_ROUTE" MODIFY ("ROUTE_NO" NOT NULL ENABLE);
  ALTER TABLE "SXS1987"."S20_1_ROUTE" MODIFY ("SOURCE_STATION_CODE" NOT NULL ENABLE);
  ALTER TABLE "SXS1987"."S20_1_ROUTE" MODIFY ("DEST_STATION_CODE" NOT NULL ENABLE);
  ALTER TABLE "SXS1987"."S20_1_ROUTE" MODIFY ("DISTANCE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table S20_1_ROUTE
--------------------------------------------------------

  ALTER TABLE "SXS1987"."S20_1_ROUTE" ADD CONSTRAINT "ROUTE_FK1" FOREIGN KEY ("SOURCE_STATION_CODE")
	  REFERENCES "SXS1987"."S20_1_STATION" ("STATION_CODE") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SXS1987"."S20_1_ROUTE" ADD CONSTRAINT "ROUTE_FK2" FOREIGN KEY ("DEST_STATION_CODE")
	  REFERENCES "SXS1987"."S20_1_STATION" ("STATION_CODE") ON DELETE CASCADE ENABLE;
